# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
 config.vm.provider "virtualbox" do |v|
  v.name = "rancher"
 end
 config.vm.box = "ubuntu/xenial64"
 config.vm.network "private_network", type: "dhcp"
 config.vm.provider "virtualbox" do |vb|
     vb.memory = "2048" 
 end
 config.vm.provision "shell", path: "script/dockerinstall.sh"
end